# Generated by Django 2.1.1 on 2018-09-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('user_name', models.CharField(max_length=256)),
            ],
        ),
    ]
